### ISSUE TITLE
Consolidate SEO functionality from our themes to a plugin

### ISSUE THREAD

**Issue by jessica-townsend** [thoughtis/cata-seo#1]
### Background
We are preparing for setting up a WordPress site that likely won't be hosted on VIP. We have several bits of code that are related to search indexing and structured data that could be consolidated into a plugin and reused for Thought Catalog, sites on ThoughtNet and this new Quote Catalog blog wherever we are able to host it.

### Details
This plugin will consolidate the following:

**Structured Data**
- Should have an open filter for breadcrumbs.
- Output structured data after post so you can append FAQs or movies to the structure that are referenced in the content.
- https://github.com/wpcomvip/thoughtnet/tree/master/plugins/cata-structured-data
- https://github.com/wpcomvip/thought-catalog/tree/master/plugins/thoughtcatalog-structured-data

**Jetpack Settings**
- This might make some assumptions about using the VIP image hosting capabilities when it produces share images. If so it should be possible to make it work for the standard Jetpack Photon CDN too.
- https://github.com/wpcomvip/thoughtnet/tree/master/themes/collective-world/includes/jetpack-settings
- https://github.com/wpcomvip/thoughtnet/tree/master/themes/creepycatalog/includes/jetpack-settings
- https://github.com/wpcomvip/thought-catalog/tree/master/themes/thoughtcatalog-2014/includes/jetpack-settings

**Robots**
- There are some specifics for custom post types that might have to stick with the individual themes.
- https://github.com/wpcomvip/thoughtnet/blob/master/themes/collective-world/includes/robots/class-robots.php
- https://github.com/wpcomvip/thoughtnet/blob/master/themes/creepycatalog/includes/robots/class-robots.php
- https://github.com/wpcomvip/thought-catalog/blob/master/themes/thoughtcatalog-2014/includes/class-search-indexing.php

**Comment by jessica-townsend** [comment]
@douglas-johnson I have the generic code for the SEO-related functionality set up here:
https://github.com/thoughtis/cata-seo/tree/issue%231/consolidate-seo-code/includes

For the share image, it looks like we currently use a setting in the customizer to select it. For block themes, the customizer won't be available. Is this something we should consider switching to an options page instead?

**Comment by douglas-johnson** [comment]
Yes that would be great
